name: BadBlockShopLinker
author: xMalware
version: 1.0
description: The best shop ever
main: fr.badblock.common.shoplinker.bukkit.ShopLinker
commands:
   shoplinker:
     description: ShopLinker main command
     aliases: [sl]