# Point de tp quand on clique sur le NPC
Course:
  world: world
  x: -20.5
  y: 81
  z: -39.5
  yaw: 180
  pitch: 0

Jump:
  world: world
  x: -115.5
  y: 82
  z: 104.5
  yaw: 0
  pitch: 0

Spleef:
  world: world
  x: -110.5
  y: 82
  z: 8.5
  yaw: 125
  pitch: 0

TirArc:
  world: world
  x: 148.5
  y: 82
  z: -89.5
  yaw: -90
  pitch: 0